### ISSUE TITLE
The term 'Invoke-SlackBot' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Platanisiotis** [markwragg/Powershell-SlackBot#9]
I've imported the module and once I tab complete Invoke-SlackBot (which does auto complete) I get the error where Invoke-SlackBot is not recognised and then it will no longer tab complete.

Have you seen this?

**Comment by markwragg** [comment]
This might have occurred if you had downloaded the module from source control directly vs installing it from the PS Gallery. This is because the Module Manifest FunctionsToExport field wasn't populated until the build process occurred. 

I've now populated FunctionsToExport manually in the module manifest so if you download the latest version it should now tab complete/locate the Invoke-SlackBot command.
